// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bai04.Models;

public partial class BacSi
{
    public int MaBs { get; set; }

    public string HoTen { get; set; }

    public string ChuyenKhoa { get; set; }

    public string Sdt { get; set; }

    public virtual ICollection<LichKham> LichKhams { get; set; } = new List<LichKham>();

    // Định dạng hiển thị: "BS. Nguyễn Văn A - Nội tổng quát" (tránh lặp BS. BS.)
    public string ThongTinHienThi
    {
        get
        {
            string ten = HoTen?.Trim() ?? "";
            if (!ten.StartsWith("BS.", StringComparison.OrdinalIgnoreCase) && 
                !ten.StartsWith("Bác sĩ", StringComparison.OrdinalIgnoreCase))
            {
                ten = $"BS. {ten}";
            }
            return $"{ten} - {ChuyenKhoa}";
        }
    }
}