namespace Bai17
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            menuStrip1 = new MenuStrip();
            mnuChucNang = new ToolStripMenuItem();
            mnuCapNhat = new ToolStripMenuItem();
            mnuPhai1 = new ToolStripMenuItem();
            mnuPhaiAll = new ToolStripMenuItem();
            mnuTrai1 = new ToolStripMenuItem();
            mnuTraiAll = new ToolStripMenuItem();
            mnuXoaA = new ToolStripMenuItem();
            mnuXoaB = new ToolStripMenuItem();
            toolStripSeparator1 = new ToolStripSeparator();
            mnuKetThuc = new ToolStripMenuItem();
            mnuThongTin = new ToolStripMenuItem();
            lblMssv = new Label();
            lblTen = new Label();
            txtTen = new TextBox();
            lblLop = new Label();
            cboLop = new ComboBox();
            btnCapNhat = new Button();
            lblLopA = new Label();
            lblLopB = new Label();
            lstLopA = new ListBox();
            lstLopB = new ListBox();
            btnPhai1 = new Button();
            btnPhaiAll = new Button();
            btnTrai1 = new Button();
            btnTraiAll = new Button();
            btnXoaA = new Button();
            btnXoaB = new Button();
            btnKetThuc = new Button();
            menuStrip1.SuspendLayout();
            SuspendLayout();
            menuStrip1.ImageScalingSize = new Size(20, 20);
            menuStrip1.Items.AddRange(new ToolStripItem[] { mnuChucNang, mnuThongTin });
            menuStrip1.Location = new Point(0, 0);
            menuStrip1.Name = "menuStrip1";
            menuStrip1.Size = new Size(670, 28);
            menuStrip1.TabIndex = 0;
            mnuChucNang.DropDownItems.AddRange(new ToolStripItem[] { mnuCapNhat, mnuPhai1, mnuPhaiAll, mnuTrai1, mnuTraiAll, mnuXoaA, mnuXoaB, toolStripSeparator1, mnuKetThuc });
            mnuChucNang.Name = "mnuChucNang";
            mnuChucNang.Size = new Size(97, 24);
            mnuChucNang.Text = "Chức năng";
            mnuCapNhat.Name = "mnuCapNhat";
            mnuCapNhat.Size = new Size(320, 26);
            mnuCapNhat.Text = "Cập nhật";
            mnuCapNhat.Click += mnuCapNhat_Click;
            mnuPhai1.Name = "mnuPhai1";
            mnuPhai1.Size = new Size(320, 26);
            mnuPhai1.Text = "Chuyển phần tử chọn sang lớp B";
            mnuPhai1.Click += mnuPhai1_Click;
            mnuPhaiAll.Name = "mnuPhaiAll";
            mnuPhaiAll.Size = new Size(320, 26);
            mnuPhaiAll.Text = "Chuyển toàn bộ sang lớp B";
            mnuPhaiAll.Click += mnuPhaiAll_Click;
            mnuTrai1.Name = "mnuTrai1";
            mnuTrai1.Size = new Size(320, 26);
            mnuTrai1.Text = "Chuyển phần tử chọn sang lớp A";
            mnuTrai1.Click += mnuTrai1_Click;
            mnuTraiAll.Name = "mnuTraiAll";
            mnuTraiAll.Size = new Size(320, 26);
            mnuTraiAll.Text = "Chuyển toàn bộ sang lớp A";
            mnuTraiAll.Click += mnuTraiAll_Click;
            mnuXoaA.Name = "mnuXoaA";
            mnuXoaA.Size = new Size(320, 26);
            mnuXoaA.Text = "Xóa lớp A";
            mnuXoaA.Click += mnuXoaA_Click;
            mnuXoaB.Name = "mnuXoaB";
            mnuXoaB.Size = new Size(320, 26);
            mnuXoaB.Text = "Xóa lớp B";
            mnuXoaB.Click += mnuXoaB_Click;
            toolStripSeparator1.Name = "toolStripSeparator1";
            toolStripSeparator1.Size = new Size(317, 6);
            mnuKetThuc.Name = "mnuKetThuc";
            mnuKetThuc.Size = new Size(320, 26);
            mnuKetThuc.Text = "Kết thúc";
            mnuKetThuc.Click += mnuKetThuc_Click;
            mnuThongTin.Name = "mnuThongTin";
            mnuThongTin.Size = new Size(90, 24);
            mnuThongTin.Text = "Thông tin";
            mnuThongTin.Click += mnuThongTin_Click;
            lblMssv.AutoSize = true;
            lblMssv.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblMssv.Location = new Point(20, 40);
            lblMssv.Name = "lblMssv";
            lblMssv.Size = new Size(130, 23);
            lblMssv.TabIndex = 1;
            lblMssv.Text = "MSSV: 6551071031";
            lblTen.AutoSize = true;
            lblTen.Location = new Point(20, 80);
            lblTen.Name = "lblTen";
            lblTen.Size = new Size(70, 20);
            lblTen.TabIndex = 2;
            lblTen.Text = "Họ và tên";
            txtTen.Location = new Point(110, 77);
            txtTen.Name = "txtTen";
            txtTen.Size = new Size(200, 27);
            txtTen.TabIndex = 3;
            lblLop.AutoSize = true;
            lblLop.Location = new Point(330, 80);
            lblLop.Name = "lblLop";
            lblLop.Size = new Size(33, 20);
            lblLop.TabIndex = 4;
            lblLop.Text = "Lớp";
            cboLop.DropDownStyle = ComboBoxStyle.DropDownList;
            cboLop.Location = new Point(380, 77);
            cboLop.Name = "cboLop";
            cboLop.Size = new Size(120, 28);
            cboLop.TabIndex = 5;
            btnCapNhat.Location = new Point(520, 75);
            btnCapNhat.Name = "btnCapNhat";
            btnCapNhat.Size = new Size(100, 30);
            btnCapNhat.TabIndex = 6;
            btnCapNhat.Text = "Cập nhật";
            btnCapNhat.UseVisualStyleBackColor = true;
            btnCapNhat.Click += btnCapNhat_Click;
            lblLopA.AutoSize = true;
            lblLopA.Location = new Point(20, 125);
            lblLopA.Name = "lblLopA";
            lblLopA.Size = new Size(49, 20);
            lblLopA.TabIndex = 7;
            lblLopA.Text = "Lớp A";
            lblLopB.AutoSize = true;
            lblLopB.Location = new Point(420, 125);
            lblLopB.Name = "lblLopB";
            lblLopB.Size = new Size(48, 20);
            lblLopB.TabIndex = 8;
            lblLopB.Text = "Lớp B";
            lstLopA.Location = new Point(20, 150);
            lstLopA.Name = "lstLopA";
            lstLopA.SelectionMode = SelectionMode.MultiExtended;
            lstLopA.Size = new Size(220, 244);
            lstLopA.TabIndex = 9;
            lstLopB.Location = new Point(420, 150);
            lstLopB.Name = "lstLopB";
            lstLopB.SelectionMode = SelectionMode.MultiExtended;
            lstLopB.Size = new Size(220, 244);
            lstLopB.TabIndex = 10;
            btnPhai1.Location = new Point(270, 175);
            btnPhai1.Name = "btnPhai1";
            btnPhai1.Size = new Size(120, 35);
            btnPhai1.TabIndex = 11;
            btnPhai1.Text = ">";
            btnPhai1.UseVisualStyleBackColor = true;
            btnPhai1.Click += btnPhai1_Click;
            btnPhaiAll.Location = new Point(270, 225);
            btnPhaiAll.Name = "btnPhaiAll";
            btnPhaiAll.Size = new Size(120, 35);
            btnPhaiAll.TabIndex = 12;
            btnPhaiAll.Text = ">>";
            btnPhaiAll.UseVisualStyleBackColor = true;
            btnPhaiAll.Click += btnPhaiAll_Click;
            btnTrai1.Location = new Point(270, 275);
            btnTrai1.Name = "btnTrai1";
            btnTrai1.Size = new Size(120, 35);
            btnTrai1.TabIndex = 13;
            btnTrai1.Text = "<";
            btnTrai1.UseVisualStyleBackColor = true;
            btnTrai1.Click += btnTrai1_Click;
            btnTraiAll.Location = new Point(270, 325);
            btnTraiAll.Name = "btnTraiAll";
            btnTraiAll.Size = new Size(120, 35);
            btnTraiAll.TabIndex = 14;
            btnTraiAll.Text = "<<";
            btnTraiAll.UseVisualStyleBackColor = true;
            btnTraiAll.Click += btnTraiAll_Click;
            btnXoaA.Location = new Point(20, 415);
            btnXoaA.Name = "btnXoaA";
            btnXoaA.Size = new Size(120, 35);
            btnXoaA.TabIndex = 15;
            btnXoaA.Text = "Xóa lớp A";
            btnXoaA.UseVisualStyleBackColor = true;
            btnXoaA.Click += btnXoaA_Click;
            btnXoaB.Location = new Point(420, 415);
            btnXoaB.Name = "btnXoaB";
            btnXoaB.Size = new Size(120, 35);
            btnXoaB.TabIndex = 16;
            btnXoaB.Text = "Xóa lớp B";
            btnXoaB.UseVisualStyleBackColor = true;
            btnXoaB.Click += btnXoaB_Click;
            btnKetThuc.Location = new Point(520, 415);
            btnKetThuc.Name = "btnKetThuc";
            btnKetThuc.Size = new Size(120, 35);
            btnKetThuc.TabIndex = 17;
            btnKetThuc.Text = "Kết thúc";
            btnKetThuc.UseVisualStyleBackColor = true;
            btnKetThuc.Click += btnKetThuc_Click;
            AcceptButton = btnCapNhat;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(670, 475);
            Controls.Add(btnKetThuc);
            Controls.Add(btnXoaB);
            Controls.Add(btnXoaA);
            Controls.Add(btnTraiAll);
            Controls.Add(btnTrai1);
            Controls.Add(btnPhaiAll);
            Controls.Add(btnPhai1);
            Controls.Add(lstLopB);
            Controls.Add(lstLopA);
            Controls.Add(lblLopB);
            Controls.Add(lblLopA);
            Controls.Add(btnCapNhat);
            Controls.Add(cboLop);
            Controls.Add(lblLop);
            Controls.Add(txtTen);
            Controls.Add(lblTen);
            Controls.Add(lblMssv);
            Controls.Add(menuStrip1);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MainMenuStrip = menuStrip1;
            MaximizeBox = false;
            Name = "Form1";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Bài 17 - Menu cho Bài 14";
            FormClosing += Form1_FormClosing;
            Load += Form1_Load;
            menuStrip1.ResumeLayout(false);
            menuStrip1.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private MenuStrip menuStrip1;
        private ToolStripMenuItem mnuChucNang;
        private ToolStripMenuItem mnuCapNhat;
        private ToolStripMenuItem mnuPhai1;
        private ToolStripMenuItem mnuPhaiAll;
        private ToolStripMenuItem mnuTrai1;
        private ToolStripMenuItem mnuTraiAll;
        private ToolStripMenuItem mnuXoaA;
        private ToolStripMenuItem mnuXoaB;
        private ToolStripSeparator toolStripSeparator1;
        private ToolStripMenuItem mnuKetThuc;
        private ToolStripMenuItem mnuThongTin;
        private Label lblMssv;
        private Label lblTen;
        private TextBox txtTen;
        private Label lblLop;
        private ComboBox cboLop;
        private Button btnCapNhat;
        private Label lblLopA;
        private Label lblLopB;
        private ListBox lstLopA;
        private ListBox lstLopB;
        private Button btnPhai1;
        private Button btnPhaiAll;
        private Button btnTrai1;
        private Button btnTraiAll;
        private Button btnXoaA;
        private Button btnXoaB;
        private Button btnKetThuc;
    }
}
